image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - pip install -r requirements_test.txt

build: off

test_script:
  - pytest --cov=smb3_eh_manip --cov-report term-missing tests/

after_test:
  - pyinstaller --noconfirm --onefile --console -n smb3_eh_manip --uac-admin app.py
  - cp -r data/ dist/
  - cp config.ini.sample dist/
  - cp README.* dist/
  - 7z a smb3_eh_manip.zip dist/*
  - 7z rn smb3_eh_manip.zip dist smb3_eh_manip

artifacts:
  - path: smb3_eh_manip.zip
    name: smb3_eh_manip

deploy:
  - provider: GitHub
    tag: dev
    release: dev
    auth_token:
      secure: 32wi9EYebbPOK8c8u2acHuSm2Gs/Mhm9nhnUOKmkuh10ftCGcdGu3yTo2PRiuuN/
    artifact: smb3_eh_manip.zip
    prerelease: true
    on:
      branch: main
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: 32wi9EYebbPOK8c8u2acHuSm2Gs/Mhm9nhnUOKmkuh10ftCGcdGu3yTo2PRiuuN/
    artifact: smb3_eh_manip.zip
    prerelease: true
    on:
      APPVEYOR_REPO_TAG: true