image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"

install:
  - pip install -r requirements_test.txt

build: off

test_script:
  - pytest --cov=smb3_eh_manip --cov-report term-missing tests/

after_test:
  - pyinstaller --noconfirm --onefile --console -n smb3_eh_manip --uac-admin app.py

artifacts:
  - path: dist\*