image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"

install:
  - pip install -r requirements_test.txt

build: off

test_script:
  - pytest --cov=smb3_eh_manip --cov-report term-missing tests/

after_test:
  - make pyinstaller

after_build:
  - 7z a smb3_eh_manip.zip dist/* 

artifacts:
  - path: smb3_eh_manip.zip
    name: smb3_eh_manip