image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"

install:
  - pip install -r requirements_test.txt

build: off

test_script:
  - pytest --cov=smb3_eh_manip --cov-report term-missing tests/

after_test:
  - pyinstaller --noconfirm --onefile --console -n smb3_eh_manip --uac-admin app.py
  - mkdir dist/smb3_eh_manip
  - mv dist/smb3_eh_mani.exe dist/smb3_eh_manip
  - cp -r data/ dist/smb3_eh_manip
	- cp config.ini.sample dist/smb3_eh_manip
	- cp README.* dist/smb3_eh_manip

artifacts:
  - path: dist\*
    name: smb3_eh_manip
    type: zip